# Generated by Django 4.2.6 on 2023-11-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userinfo',
            new_name='Products',
        ),
    ]
