# Generated by Django 4.2.6 on 2023-11-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_userinfo_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
